/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.SeguridadArchivos;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.awt.Color;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;

import Modelo.InventarioCRUD;
import Modelo.InventarioTemporalCRUD;
import Vista.libreriaForm;

/**
 *
 * @author E2112
 */
public class InventarioForm extends javax.swing.JFrame {
    public List<Double> precios = new ArrayList<>();
    private List<Map<String, Object>> libros;
    private DefaultTableModel modeloTabla;

    int xMouse, yMouse;
    int id;

    /**
     * Creates new form InventarioForm
     */
    public InventarioForm() {
        initComponents();
        cargarDatos();
        configurarBusqueda();
        ajustarTamanioColumnas();
        configurarTabla(false);
        setTime();
    }
    
    public void InitInventario(int id) {
        this.id = id;
        this.setSize(853, 792);
        this.setMaximumSize(this.getSize());
        this.setMinimumSize(this.getSize());
        this.setPreferredSize(this.getSize());
        this.setLocationRelativeTo(null);
        this.setCloseOperation();
        this.getContentPane().setBackground(Color.WHITE);
        this.setVisible(true);
    }

    private void setCloseOperation() {
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                SeguridadArchivos.EncriptarArchivos();
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jTxtDate = new javax.swing.JLabel();
        jTxtime = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Modificar = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        headerinventory = new javax.swing.JPanel();
        Codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Estadisticas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Eliminar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        CodEliminar = new javax.swing.JTextField();
        Agregar = new javax.swing.JToggleButton();
        CodigoAg = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CantidadAg = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PrecioAg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AutorAg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        NombreAg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("INVENTARIO");
        jLabel11.setToolTipText("");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, 45));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inventario-disponible128.png"))); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 160, 140));

        btnVolver.setBackground(new java.awt.Color(204, 204, 204));
        btnVolver.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(51, 51, 51));
        btnVolver.setText("VOLVER AL MENÚ");
        btnVolver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        jPanel3.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 720, 120, 40));

        jTxtDate.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jTxtDate.setForeground(new java.awt.Color(255, 255, 255));
        jTxtDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jTxtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 180, 41));

        jTxtime.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jTxtime.setForeground(new java.awt.Color(255, 255, 255));
        jTxtime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jTxtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, 123, 39));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 790));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Modificar.setBackground(new java.awt.Color(51, 51, 51));
        Modificar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        Modificar.setForeground(new java.awt.Color(255, 255, 255));
        Modificar.setText("MODIFICAR");
        Modificar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        Modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        jPanel1.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 90, 30));

        Guardar.setBackground(new java.awt.Color(51, 51, 51));
        Guardar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("GUARDAR");
        Guardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        Guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 90, 30));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 75, 75)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Obra", "Autor", "Precio", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Short.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 590, 214));

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel13.setText("Cerrar");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        headerinventory.setBackground(new java.awt.Color(255, 255, 255));
        headerinventory.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerinventoryMouseDragged(evt);
            }
        });
        headerinventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerinventoryMousePressed(evt);
            }
        });
        headerinventory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Codigo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(75, 75, 75), 1, true));
        headerinventory.add(Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 100, 30));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 16)); // NOI18N
        jLabel2.setText("Filtrar por Codigo:");
        headerinventory.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 19, 110, 30));

        Nombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(75, 75, 75), 1, true));
        headerinventory.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 183, 30));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 16)); // NOI18N
        jLabel1.setText("Filtrar por Nombre:");
        headerinventory.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 19, 110, 30));

        Estadisticas.setBackground(new java.awt.Color(51, 51, 51));
        Estadisticas.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        Estadisticas.setForeground(new java.awt.Color(255, 255, 255));
        Estadisticas.setText("ESTADISTICAS");
        Estadisticas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        Estadisticas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Estadisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EstadisticasMouseClicked(evt);
            }
        });
        Estadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadisticasActionPerformed(evt);
            }
        });
        headerinventory.add(Estadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 120, 30));

        jPanel1.add(headerinventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(-219, 0, 860, 80));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 635, 360));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Eliminar.setBackground(new java.awt.Color(51, 51, 51));
        Eliminar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar.setText("ELIMINAR LIBRO");
        Eliminar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        Eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel2.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 120, 30));

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 16)); // NOI18N
        jLabel10.setText("Código:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 50, -1));

        CodEliminar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(25, 25, 25), 1, true));
        CodEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(CodEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 105, 25));

        Agregar.setBackground(new java.awt.Color(51, 51, 51));
        Agregar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        Agregar.setForeground(new java.awt.Color(255, 255, 255));
        Agregar.setText("AGREGAR LIBRO");
        Agregar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        Agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        jPanel2.add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, 30));

        CodigoAg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jPanel2.add(CodigoAg, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 128, 105, 25));

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 16)); // NOI18N
        jLabel8.setText("Codigo:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 60, -1));

        CantidadAg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jPanel2.add(CantidadAg, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 128, 105, 25));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 16)); // NOI18N
        jLabel7.setText("Cantidad:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 60, -1));

        PrecioAg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jPanel2.add(PrecioAg, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 128, 105, 25));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 16)); // NOI18N
        jLabel6.setText("Precio:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 50, -1));

        AutorAg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jPanel2.add(AutorAg, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 78, 220, 25));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 16)); // NOI18N
        jLabel5.setText("Autor:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 40, -1));

        NombreAg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        NombreAg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreAgActionPerformed(evt);
            }
        });
        jPanel2.add(NombreAg, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 78, 220, 25));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 16)); // NOI18N
        jLabel4.setText("Nombre:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, -1));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AGREGAR NUEVO LIBRO");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 590, 60));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ELIMINAR UN LIBRO");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 123, -1));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 590, 40));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 630, 420));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 635, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // Que la tabla sea editable
        jTable1.setDefaultEditor(Object.class, new javax.swing.DefaultCellEditor(new javax.swing.JTextField()));
    }//GEN-LAST:event_ModificarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        //Guardar todos los cambios hechos en la tabla y exportarlos al json
        ObjectMapper mapper = new ObjectMapper();
        try {
            List<Map<String, Object>> libros = new ArrayList<>();
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                Map<String, Object> libro = Map.of(
                    "cod", jTable1.getValueAt(i, 0),
                    "nombre", jTable1.getValueAt(i, 1),
                    "autor", jTable1.getValueAt(i, 2),
                    "precio", jTable1.getValueAt(i, 3),
                    "cantidad", jTable1.getValueAt(i, 4)
                );
                libros.add(libro);
            }
            //Crear un array con los precios
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                precios.add(Double.parseDouble(jTable1.getValueAt(i, 3).toString()));
            }
            Modelo.InventarioCRUD inventarioCRUD = new InventarioCRUD();
            inventarioCRUD.actualizarTabla((ArrayList) libros);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void NombreAgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreAgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreAgActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // si alguno de los campos est vacio que el boton no haga nada y emita un mensaje
        if (NombreAg.getText().isEmpty() || AutorAg.getText().isEmpty() || PrecioAg.getText().isEmpty() || CantidadAg.getText().isEmpty() || CodigoAg.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor llene todos los campos");
            return;
        }
        else {
            String nombre = NombreAg.getText();
            String autor = AutorAg.getText();
            try {
                Double.parseDouble(PrecioAg.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese un valor numerico en el campo Precio");
                return;
            }
            try {
                Short.parseShort(CantidadAg.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese un valor numerico en el campo Cantidad");
                return;
            }
            double precio = Double.parseDouble(PrecioAg.getText());
            short cantidad = Short.parseShort(CantidadAg.getText());
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                if (CodigoAg.getText().equals(jTable1.getValueAt(i, 0).toString())) {
                    JOptionPane.showMessageDialog(null, "El codigo ya existe, por favor ingrese uno diferente");
                    return;
                }
            }
            String cod = CodigoAg.getText();
            InventarioCRUD inventarioCRUD = new InventarioCRUD();
            InventarioTemporalCRUD inventarioTemporalCRUD = new InventarioTemporalCRUD();
            inventarioCRUD.agregarInventario(new Modelo.mdInventario(nombre, autor, precio, cantidad, cod));
            inventarioTemporalCRUD.agregarInventarioTemporal(new Modelo.mdInventario(nombre, autor, precio, cantidad, cod));
            JOptionPane.showMessageDialog(null, "Libro agregado exitosamente");
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            cargarDatos();
            NombreAg.setText("");
            AutorAg.setText("");
            PrecioAg.setText("");
            CantidadAg.setText("");
            CodigoAg.setText("");
        }
    }//GEN-LAST:event_AgregarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        if (CodEliminar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el codigo del libro que desea eliminar");
        }else{
            String cod = CodEliminar.getText();
            boolean existe = false;
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                if (cod.equals(jTable1.getValueAt(i, 0).toString())) {
                    existe = true;
                    break;
                }
            }
            if (!existe) {
                JOptionPane.showMessageDialog(null, "El libro con el codigo " + cod + " no existe");
                return;
            } else {
                InventarioCRUD inventarioCRUD = new InventarioCRUD();
                InventarioTemporalCRUD inventarioTemporalCRUD = new InventarioTemporalCRUD();
                inventarioCRUD.eliminarInventario(cod);
                inventarioTemporalCRUD.eliminarInventarioTemporal(cod);
                JOptionPane.showMessageDialog(null, "Libro eliminado exitosamente");
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                cargarDatos();
                CodEliminar.setText("");
            }
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void CodEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodEliminarActionPerformed

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        // TODO add your handling code here:
        dispose();
        MenuAdministradorForm menuAdmin = new MenuAdministradorForm();
        menuAdmin.InitMenuAdministrador(id);
    }//GEN-LAST:event_btnVolverMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        SeguridadArchivos.EncriptarArchivos();
        System.exit(0);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed

    }//GEN-LAST:event_jPanel1MousePressed

    private void headerinventoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerinventoryMousePressed
        xMouse =evt.getX();
        yMouse =evt.getY();
    }//GEN-LAST:event_headerinventoryMousePressed

    private void headerinventoryMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerinventoryMouseDragged
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_headerinventoryMouseDragged

    private void EstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadisticasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadisticasActionPerformed

    private void EstadisticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstadisticasMouseClicked
        // TODO add your handling code here:
        dispose();
        EstadisticasForm estadisticas = new EstadisticasForm();
        estadisticas.InitEstadisticas(this.id);
    }//GEN-LAST:event_EstadisticasMouseClicked


    
    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventarioForm().setVisible(true);
            }
        });
    }
    
    private void cargarDatos() {
        ObjectMapper mapper = new ObjectMapper();
        try {
            libros = mapper.readValue(new File("data/json/inventario.json"), new TypeReference<List<Map<String, Object>>>() {});
            modeloTabla = (DefaultTableModel) jTable1.getModel();
            libros.forEach(libro -> modeloTabla.addRow(new Object[]{
                libro.get("cod"), 
                libro.get("nombre"), 
                libro.get("autor"), 
                libro.get("precio"), 
                libro.get("cantidad")
            }));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void configurarBusqueda() {
        Nombre.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                filtrarTabla();
            }
        });

        Codigo.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                filtrarTabla();
            }
        });
    }

    private void filtrarTabla() {
        String textoCod = Codigo.getText().toLowerCase();
        String textoNombre = Nombre.getText().toLowerCase();
        List<Map<String, Object>> librosFiltrados = libros.stream()
            .filter(libro -> libro.get("cod").toString().toLowerCase().contains(textoCod) && 
                             libro.get("nombre").toString().toLowerCase().contains(textoNombre))
            .collect(Collectors.toList());

        modeloTabla.setRowCount(0);
        librosFiltrados.forEach(libro -> modeloTabla.addRow(new Object[]{
            libro.get("cod"), 
            libro.get("nombre"), 
            libro.get("autor"), 
            libro.get("precio"), 
            libro.get("cantidad")
        }));
    }

    private void ajustarTamanioColumnas() {
        TableColumn columnauno = jTable1.getColumnModel().getColumn(0);
        columnauno.setPreferredWidth(60); // Ancho preferido en píxeles

        TableColumn columnados = jTable1.getColumnModel().getColumn(1);
        columnados.setPreferredWidth(150);

        TableColumn columnatres = jTable1.getColumnModel().getColumn(2);
        columnatres.setPreferredWidth(170);

        TableColumn columnacuatro = jTable1.getColumnModel().getColumn(3);
        columnacuatro.setPreferredWidth(80);

        jTable1.setRowHeight(30);

        jTable1.repaint();
    }

    private void configurarTabla(boolean editable) {
        if (editable) {
            // Permitir la edición solo en las columnas de Precio y Cantidad
            jTable1.setDefaultEditor(Object.class, new javax.swing.DefaultCellEditor(new javax.swing.JTextField()));
        } else {
            jTable1.setDefaultEditor(Object.class, null);
        }
    }

    public void setTime(){
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true){
                    try{
                        Thread.sleep(1000);
                    } catch (InterruptedException ex){
                        Logger.getLogger(libreriaForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    Date date = new Date();
                    SimpleDateFormat tf = new SimpleDateFormat("h:mm:ss a");
                    SimpleDateFormat df = new SimpleDateFormat("EEEE, dd-MM-yyyy");
                    String time = tf.format(date);
                    jTxtime.setText(time.split(" ")[0]+" " + time.split(" ")[1]);
                    jTxtDate.setText(df.format(date));
                }
            }
        }).start();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Agregar;
    private javax.swing.JTextField AutorAg;
    private javax.swing.JTextField CantidadAg;
    private javax.swing.JTextField CodEliminar;
    private javax.swing.JTextField Codigo;
    private javax.swing.JTextField CodigoAg;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Estadisticas;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Modificar;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField NombreAg;
    private javax.swing.JTextField PrecioAg;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel headerinventory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jTxtDate;
    private javax.swing.JLabel jTxtime;
    // End of variables declaration//GEN-END:variables
}
