/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.CtrlFacturaVentas;
import Controlador.CtrlRegistro;
import Controlador.SeguridadArchivos;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author user
 */
public class ListaFacturasForm extends javax.swing.JFrame {

    /**
     * Creates new form ListaFacturasForm
     */

    int id;

    public ListaFacturasForm() {
        initComponents();
        setTime();
        setDocumentos();
    }
    
    public void InitListaFacturas(int id) {
        this.id = id;
        this.setSize(1000, 900);
        this.setMaximumSize(this.getSize());
        this.setMinimumSize(this.getSize());
        this.setPreferredSize(this.getSize());
        this.setLocationRelativeTo(null);
        this.setCloseOperation();
        this.getContentPane().setBackground(Color.WHITE);
        this.setVisible(true);
    }

    private void setCloseOperation() {
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                SeguridadArchivos.EncriptarArchivos();
                System.exit(0);
            }
        });
    }
    
    private void setDocumentos() {
        AreaFacturas.setText("");
        DefaultListModel<String> model = new DefaultListModel<>();
        String[] documentos = CtrlFacturaVentas.LeerDocumentos();
        int i = 0;
        for (String documento : documentos) {
            model.add(i++, documento);
        }
        ListaDocumentos.setModel(model);
        ListaDocumentos.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                JList list = (JList)evt.getSource();
                if (evt.getClickCount() == 2) { // Doble-clic detectado
                    int index = list.locationToIndex(evt.getPoint());
                    // Aquí puedes manejar el evento de doble clic.
                    try {
                        Object item = model.getElementAt(index);
                        String txtFin = "";
                        String txt = CtrlFacturaVentas.leerFacturaporID(item.toString());
                        String infoUsuario = CtrlRegistro.TomarInformacionUsuario(item.toString());
                        if (!infoUsuario.isEmpty()) {
                            txtFin = "Información del usuario: \n" + infoUsuario + "\n\n" + txt;
                        }
                        else {
                            txtFin = "Información del usuario: \nEl usuario ha sido eliminado." + "\n\n" + txt;
                        }
                        if (txt.isEmpty()) {
                            AreaFacturas.setText("Información del usuario: \n" + infoUsuario + "\n\nEl usuario no ha comprado nada.");
                        } else {
                            AreaFacturas.setText(txtFin);
                        }
                        //Inicia el scroll desde el inicio
                        AreaFacturas.setCaretPosition(0);
                    }catch (Exception ignored) {}
                }
            }
        });
    }

    private void setDocumentos(String[] documentos) {
        AreaFacturas.setText("");
        String txtFin = "";
        DefaultListModel<String> model = new DefaultListModel<>();
        int i = 0;
        for (String documento : documentos) {
            model.add(i++, documento);
        }
        ListaDocumentos.setModel(model);
        if (documentos.length == 1) {
            String txt = CtrlFacturaVentas.leerFacturaporID(documentos[0]);
            String infoUsuario = CtrlRegistro.TomarInformacionUsuario(documentos[0]);
            if (!infoUsuario.isEmpty()) {
                txtFin = "Información del usuario: \n" + infoUsuario + "\n\n" + txt;
            }
            else {
                txtFin = "Información del usuario: \nEl usuario ha sido eliminado." + "\n\n" + txt;
            }
            if (txt.isEmpty()) {
                AreaFacturas.setText("Información del usuario: \n" + infoUsuario + "\n\nEl usuario no ha comprado nada.");
            } else {
                AreaFacturas.setText(txtFin);
            }
            //Inicia el scroll desde el inicio
            AreaFacturas.setCaretPosition(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtime = new javax.swing.JLabel();
        jTxtDate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaFacturas = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaDocumentos = new javax.swing.JList<>();
        btnEliminarFactura = new javax.swing.JButton();
        Codigo = new javax.swing.JLabel();
        codigoField = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        buscarField = new javax.swing.JTextField();
        lblBuscar = new javax.swing.JLabel();
        lblBuscarUsuario = new javax.swing.JLabel();
        btnInsertarFactura = new javax.swing.JButton();
        lblIDañadirFactura = new javax.swing.JLabel();
        IDAnadirFacturaField = new javax.swing.JTextField();
        btnBuscarDocumento = new javax.swing.JButton();
        documentoField = new javax.swing.JTextField();
        btnRefrescar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        lblEliminarUser = new javax.swing.JLabel();
        btnEliminarUsuario = new javax.swing.JButton();
        eliminarUsuarioField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(235, 235, 235));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel1.setText("Librería");

        jTxtime.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jTxtime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTxtDate.setFont(new java.awt.Font("Poppins", 1, 17)); // NOI18N
        jTxtDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 443, Short.MAX_VALUE)
                .addComponent(jTxtime, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jTxtDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTxtime, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        AreaFacturas.setEditable(false);
        AreaFacturas.setColumns(20);
        AreaFacturas.setRows(5);
        jScrollPane1.setViewportView(AreaFacturas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 340, 510));

        ListaDocumentos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ListaDocumentos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 300, 510));

        btnEliminarFactura.setText("Eliminar Factura");
        btnEliminarFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarFacturaMouseClicked(evt);
            }
        });
        getContentPane().add(btnEliminarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 693, -1, 30));

        Codigo.setText("Codigo: ");
        getContentPane().add(Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 700, -1, -1));

        codigoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codigoFieldKeyReleased(evt);
            }
        });
        getContentPane().add(codigoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 692, 140, 30));

        btnBuscar.setText("Buscar");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 120, -1, -1));

        buscarField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarFieldKeyReleased(evt);
            }
        });
        getContentPane().add(buscarField, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 120, 150, -1));

        lblBuscar.setText("Buscar Factura por Codigo: ");
        getContentPane().add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, -1, -1));

        lblBuscarUsuario.setText("Buscar usuario por documento: ");
        getContentPane().add(lblBuscarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        btnInsertarFactura.setText("Agregar Factura");
        btnInsertarFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarFacturaMouseClicked(evt);
            }
        });
        getContentPane().add(btnInsertarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 710, -1, 30));

        lblIDañadirFactura.setText("ID del usuario a añadir factura: (Si no existe, se agregará)");
        getContentPane().add(lblIDañadirFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 680, 400, -1));

        IDAnadirFacturaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                IDAnadirFacturaFieldKeyReleased(evt);
            }
        });
        getContentPane().add(IDAnadirFacturaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 710, 140, 30));

        btnBuscarDocumento.setText("Buscar");
        btnBuscarDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarDocumentoMouseClicked(evt);
            }
        });
        getContentPane().add(btnBuscarDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        documentoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                documentoFieldKeyReleased(evt);
            }
        });
        getContentPane().add(documentoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 160, -1));

        btnRefrescar.setText("Refrescar");
        btnRefrescar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefrescarMouseClicked(evt);
            }
        });
        getContentPane().add(btnRefrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 60, -1, -1));

        btnVolver.setText("Volver al Menu");
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        lblEliminarUser.setText("ID de usuario a eliminar: ");
        getContentPane().add(lblEliminarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 760, 140, 30));

        btnEliminarUsuario.setText("Eliminar Usuario");
        btnEliminarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarUsuarioMouseClicked(evt);
            }
        });
        getContentPane().add(btnEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 760, 120, 30));

        eliminarUsuarioField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                eliminarUsuarioFieldKeyReleased(evt);
            }
        });
        getContentPane().add(eliminarUsuarioField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 760, 140, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarFacturaMouseClicked
        // TODO add your handling code here:
        String codigo = codigoField.getText();
        if (codigo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un código de factura");
            return;
        }
        int res = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar la factura?", "Eliminar Factura", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            CtrlFacturaVentas.EliminarFactura(codigo);
            codigoField.setText("");
            setDocumentos();
        } else {
            JOptionPane.showMessageDialog(null, "Operación cancelada");
        }
    }//GEN-LAST:event_btnEliminarFacturaMouseClicked

    private void btnInsertarFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarFacturaMouseClicked
        // TODO add your handling code here:
        String id = IDAnadirFacturaField.getText();
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un ID");
            return;
        }
        boolean valID = CtrlRegistro.validarId(id);
        if (!valID) {
            return;
        }
        boolean existe = CtrlRegistro.consultarUsuario(id) != null;
        if (!existe) {
            int res = JOptionPane.showConfirmDialog(null, "El usuario no existe. Debera ser registrado: \n" +
                    "¿Registrar al usuario como Admin?", "Agregar Factura", JOptionPane.YES_NO_OPTION);
            if (res == JOptionPane.YES_OPTION) {
                dispose();
                RegistroUsuarioForm registroUsuario = new RegistroUsuarioForm();
                registroUsuario.InitRegister(true, id, true);
            } else if (res == JOptionPane.NO_OPTION) {
                dispose();
                RegistroUsuarioForm registroUsuario = new RegistroUsuarioForm();
                registroUsuario.InitRegister(false, id, true);
            }
            else {
                JOptionPane.showMessageDialog(null, "Operación cancelada");
            }
        }
        else {
            dispose();
            libreriaForm libreria = new libreriaForm();
            libreria.InitLibreria(Integer.parseInt(id), true);
        }
    }//GEN-LAST:event_btnInsertarFacturaMouseClicked

    private void LimpiarCampos() {
        AreaFacturas.setText("");
        codigoField.setText("");
        buscarField.setText("");
        documentoField.setText("");
        IDAnadirFacturaField.setText("");
    }

    private void documentoFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_documentoFieldKeyReleased
        // TODO add your handling code here:
        String documento = documentoField.getText();
        String[] docsFiltrados;
        docsFiltrados = CtrlRegistro.FiltrarUsuario(documento, documento.length());
        setDocumentos(docsFiltrados);
    }//GEN-LAST:event_documentoFieldKeyReleased

    private void btnBuscarDocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarDocumentoMouseClicked
        // TODO add your handling code here:
        String documento = documentoField.getText();
        String[] doc = new String[1];
        if (CtrlRegistro.consultarUsuario(documento) != null) {
            doc[0] = CtrlRegistro.consultarUsuario(documento).getId();
            setDocumentos(doc);
        }
    }//GEN-LAST:event_btnBuscarDocumentoMouseClicked

    private void buscarFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarFieldKeyReleased
        // TODO add your handling code here:
        FiltrarCodigo(buscarField);
    }//GEN-LAST:event_buscarFieldKeyReleased

    private void FiltrarCodigo(JTextField Field) {
        String codigo = Field.getText();
        String txt = CtrlFacturaVentas.leerFacturaporCodigo(codigo);
        String infoUsuario = CtrlRegistro.TomarInformacionUsuario(TomarID(txt));
        if (infoUsuario.isEmpty()) {
            infoUsuario = "El usuario ha sido eliminado del sistema.";
        }
        else {
            infoUsuario = "Información del usuario: \n" + infoUsuario;
        }
        if (txt.isEmpty()) {
            AreaFacturas.setText("No se encontró la factura");
        } else {
            AreaFacturas.setText(infoUsuario + "\n\n" + txt);
        }
    }


    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
        String codigo = buscarField.getText();
        String txt = CtrlFacturaVentas.leerFacturaporCodigo(codigo);
        if (txt.isEmpty()) {
            AreaFacturas.setText("No se encontró la factura");
        } else {
            AreaFacturas.setText(txt);
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void codigoFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoFieldKeyReleased
        // TODO add your handling code here:
        FiltrarCodigo(codigoField);
    }//GEN-LAST:event_codigoFieldKeyReleased

    private String TomarID(String txt) {
        String[] lines = txt.split("\n");
        for (String line : lines) {
            if (line.contains("ID:")) {
                return line.split(" ")[1];
            }
        }
        return "";
    }


    private void IDAnadirFacturaFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDAnadirFacturaFieldKeyReleased
        // TODO add your handling code here:
        String documento = IDAnadirFacturaField.getText();
        String[] docsFiltrados;
        docsFiltrados = CtrlRegistro.FiltrarUsuario(documento, documento.length());
        setDocumentos(docsFiltrados);
    }//GEN-LAST:event_IDAnadirFacturaFieldKeyReleased

    private void btnRefrescarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefrescarMouseClicked
        // TODO add your handling code here:
        LimpiarCampos();
        setDocumentos();
    }//GEN-LAST:event_btnRefrescarMouseClicked

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        // TODO add your handling code here:
        dispose();
        MenuAdministradorForm menuAdmin = new MenuAdministradorForm();
        menuAdmin.InitMenuAdministrador(this.id);
    }//GEN-LAST:event_btnVolverMouseClicked

    private void eliminarUsuarioFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eliminarUsuarioFieldKeyReleased
        // TODO add your handling code here:
        String documento = eliminarUsuarioField.getText();
        String[] docsFiltrados;
        docsFiltrados = CtrlRegistro.FiltrarUsuario(documento, documento.length());
        setDocumentos(docsFiltrados);
    }//GEN-LAST:event_eliminarUsuarioFieldKeyReleased

    private void btnEliminarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioMouseClicked
        // TODO add your handling code here:
        String documento = eliminarUsuarioField.getText();
        if (documento.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un documento");
            return;
        }
        int res = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar el usuario?", "Eliminar Usuario", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            CtrlRegistro.EliminarUsuario(documento);
            LimpiarCampos();
            eliminarUsuarioField.setText("");
            setDocumentos();
        } else {
            JOptionPane.showMessageDialog(null, "Operación cancelada");
        }
    }//GEN-LAST:event_btnEliminarUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaFacturasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaFacturasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaFacturasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaFacturasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaFacturasForm().setVisible(true);
            }
        });
    }
    
    
    public void setTime(){
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true){
                    try{
                        Thread.sleep(1000);
                    } catch (InterruptedException ex){
                        Logger.getLogger(libreriaForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    Date date = new Date();
                    SimpleDateFormat tf = new SimpleDateFormat("h:mm:ss a");
                    SimpleDateFormat df = new SimpleDateFormat("EEEE, dd-MM-yyyy");
                    String time = tf.format(date);
                    jTxtime.setText(time.split(" ")[0]+" " + time.split(" ")[1]);
                    jTxtDate.setText(df.format(date));
                }
            }
        }).start();
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaFacturas;
    private javax.swing.JLabel Codigo;
    private javax.swing.JTextField IDAnadirFacturaField;
    private javax.swing.JList<String> ListaDocumentos;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarDocumento;
    private javax.swing.JButton btnEliminarFactura;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnInsertarFactura;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JTextField buscarField;
    private javax.swing.JTextField codigoField;
    private javax.swing.JTextField documentoField;
    private javax.swing.JTextField eliminarUsuarioField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jTxtDate;
    private javax.swing.JLabel jTxtime;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblBuscarUsuario;
    private javax.swing.JLabel lblEliminarUser;
    private javax.swing.JLabel lblIDañadirFactura;
    // End of variables declaration//GEN-END:variables
}
